import fs from "fs-extra";
import path from "path";

export async function generateLayout(
  projectPath: string,
  features: string[]
): Promise<void> {
  const hasAuth = features.includes("auth");
  const hasDataFetching = features.includes("dataFetching");
  const hasConvex = features.includes("convex");

  const imports: string[] = [`import type { Metadata } from "next"`, `import "./globals.css"`];
  const wrappers: string[] = [];

  if (hasAuth) {
    imports.push(`import { ClerkProvider } from "@clerk/nextjs"`);
    wrappers.push("ClerkProvider");
  }

  if (hasConvex) {
    imports.push(`import { ConvexClientProvider } from "@/providers/convex-provider"`);
    wrappers.push("ConvexClientProvider");
  }

  if (hasDataFetching) {
    imports.push(`import { QueryProvider } from "@/providers/query-provider"`);
    wrappers.push("QueryProvider");
  }

  const metadataBlock = `
export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create-next-template",
};`;

  function wrapChildren(wrappers: string[], content: string): string {
    if (wrappers.length === 0) return content;
    const [first, ...rest] = wrappers;
    const inner = wrapChildren(rest, content);
    return `<${first}>\n        ${inner}\n      </${first}>`;
  }

  const body = wrapChildren(wrappers, "{children}");

  const layoutContent = `${imports.join("\n")}
${metadataBlock}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        ${body}
      </body>
    </html>
  );
}
`;

  const appDir = path.join(projectPath, "app");
  await fs.ensureDir(appDir);
  await fs.writeFile(path.join(appDir, "layout.tsx"), layoutContent);
}
